Repository 32nd-GO-SOPT-SOPKATHON-13/SOPKATHON-13-iOS, pull requests merged in 2023-05, with the labels that each got.

#2 [Setting] #1 - 초기세팅
  .gitignore
  SOPKATON-TEAM13/SOPKATON-TEAM13.xcodeproj/project.pbxproj
  SOPKATON-TEAM13/SOPKATON-TEAM13.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  SOPKATON-TEAM13/SOPKATON-TEAM13.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  SOPKATON-TEAM13/SOPKATON-TEAM13.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  SOPKATON-TEAM13/SOPKATON-TEAM13/Application/AppDelegate.swift
  SOPKATON-TEAM13/SOPKATON-TEAM13/Application/SceneDelegate.swift
  SOPKATON-TEAM13/SOPKATON-TEAM13/Base.lproj/Main.storyboard
  SOPKATON-TEAM13/SOPKATON-TEAM13/Data/DTO/DTO.swift
  SOPKATON-TEAM13/SOPKATON-TEAM13/Data/Model/Model.swift
  SOPKATON-TEAM13/SOPKATON-TEAM13/Info.plist
  SOPKATON-TEAM13/SOPKATON-TEAM13/Network/NetworkResult.swift
  SOPKATON-TEAM13/SOPKATON-TEAM13/Presentation/Main/Cell/MainCell.swift
  SOPKATON-TEAM13/SOPKATON-TEAM13/Presentation/Main/View/Main.swift
  SOPKATON-TEAM13/SOPKATON-TEAM13/Presentation/Main/ViewController/ViewController.swift
  SOPKATON-TEAM13/SOPKATON-TEAM13/Resource/AssetCatalog/Assets.xcassets/AccentColor.colorset/Contents.json
  SOPKATON-TEAM13/SOPKATON-TEAM13/Resource/AssetCatalog/Assets.xcassets/AppIcon.appiconset/Contents.json
  SOPKATON-TEAM13/SOPKATON-TEAM13/Resource/AssetCatalog/Assets.xcassets/Contents.json
  SOPKATON-TEAM13/SOPKATON-TEAM13/Resource/AssetCatalog/Color.xcassets/Contents.json
  SOPKATON-TEAM13/SOPKATON-TEAM13/Resource/AssetCatalog/Color.xcassets/gray1.colorset/Contents.json
  SOPKATON-TEAM13/SOPKATON-TEAM13/Resource/AssetCatalog/Color.xcassets/gray2.colorset/Contents.json
  SOPKATON-TEAM13/SOPKATON-TEAM13/Resource/AssetCatalog/Color.xcassets/gray3.colorset/Contents.json
  SOPKATON-TEAM13/SOPKATON-TEAM13/Resource/AssetCatalog/Color.xcassets/gray4.colorset/Contents.json
  SOPKATON-TEAM13/SOPKATON-TEAM13/Resource/AssetCatalog/Color.xcassets/gray5.colorset/Contents.json
  SOPKATON-TEAM13/SOPKATON-TEAM13/Resource/AssetCatalog/Color.xcassets/gray6.colorset/Contents.json
  SOPKATON-TEAM13/SOPKATON-TEAM13/Resource/AssetCatalog/Color.xcassets/gray7.colorset/Contents.json
  SOPKATON-TEAM13/SOPKATON-TEAM13/Resource/AssetCatalog/Color.xcassets/gray8.colorset/Contents.json
  SOPKATON-TEAM13/SOPKATON-TEAM13/Resource/AssetCatalog/Color.xcassets/gray9.colorset/Contents.json
  SOPKATON-TEAM13/SOPKATON-TEAM13/Resource/AssetCatalog/Color.xcassets/white.colorset/Contents.json
  SOPKATON-TEAM13/SOPKATON-TEAM13/Resource/Base.lproj/LaunchScreen.storyboard
  SOPKATON-TEAM13/SOPKATON-TEAM13/Resource/Font/Font.swift
  SOPKATON-TEAM13/SOPKATON-TEAM13/Utils/CustomClass/CustomClass.swift
  SOPKATON-TEAM13/SOPKATON-TEAM13/Utils/Extension/NSObject+.swift
  SOPKATON-TEAM13/SOPKATON-TEAM13/Utils/Extension/String+.swift
  SOPKATON-TEAM13/SOPKATON-TEAM13/Utils/Extension/UIButton+.swift
  SOPKATON-TEAM13/SOPKATON-TEAM13/Utils/Extension/UICollectionView+.swift
  SOPKATON-TEAM13/SOPKATON-TEAM13/Utils/Extension/UIFont+.swift
  SOPKATON-TEAM13/SOPKATON-TEAM13/Utils/Extension/UIImage+.swift
  SOPKATON-TEAM13/SOPKATON-TEAM13/Utils/Extension/UIImageView+.swift
  SOPKATON-TEAM13/SOPKATON-TEAM13/Utils/Extension/UILabel+.swift
  SOPKATON-TEAM13/SOPKATON-TEAM13/Utils/Extension/UIStackView+.swift
  SOPKATON-TEAM13/SOPKATON-TEAM13/Utils/Extension/UITabBar+.swift
  SOPKATON-TEAM13/SOPKATON-TEAM13/Utils/Extension/UITableView+.swift
  SOPKATON-TEAM13/SOPKATON-TEAM13/Utils/Extension/UITextField+.swift
  SOPKATON-TEAM13/SOPKATON-TEAM13/Utils/Extension/UIView+.swift
  SOPKATON-TEAM13/SOPKATON-TEAM13/Utils/Extension/UIViewController+.swift
  SOPKATON-TEAM13/SOPKATON-TEAM13/Utils/NameSpace/Color.swift
  SOPKATON-TEAM13/SOPKATON-TEAM13/Utils/NameSpace/Image.swift
Labels: Setting, 🐸 정

#7 [Setting] #6 - 폰트 사용 extension 추가
  SOPKATON-TEAM13/SOPKATON-TEAM13.xcodeproj/project.pbxproj
  SOPKATON-TEAM13/SOPKATON-TEAM13.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  SOPKATON-TEAM13/SOPKATON-TEAM13/Utils/Extension/UIFont+.swift
  SOPKATON-TEAM13/SOPKATON-TEAM13/Utils/Extension/UIImage+.swift
  SOPKATON-TEAM13/SOPKATON-TEAM13/Utils/Extension/UILabel+.swift
Labels: Setting, 🦊 규보

#8 [Fix] #3 - 폴더링
  SOPKATON-TEAM13/SOPKATON-TEAM13.xcodeproj/project.pbxproj
  SOPKATON-TEAM13/SOPKATON-TEAM13/Data/DTO/DTO.swift
  SOPKATON-TEAM13/SOPKATON-TEAM13/Data/DTO/History/HistoryResponse.swift
  SOPKATON-TEAM13/SOPKATON-TEAM13/Data/DTO/Main/MainResponse.swift
  SOPKATON-TEAM13/SOPKATON-TEAM13/Data/DTO/Notice/NoticeResponse.swift
  SOPKATON-TEAM13/SOPKATON-TEAM13/Data/DTO/SignUp/SignUpResponse.swift
  SOPKATON-TEAM13/SOPKATON-TEAM13/Data/Model/History/HistoryModel.swift
  SOPKATON-TEAM13/SOPKATON-TEAM13/Data/Model/Main/MainModel.swift
  SOPKATON-TEAM13/SOPKATON-TEAM13/Data/Model/Model.swift
  SOPKATON-TEAM13/SOPKATON-TEAM13/Data/Model/Notice/NoticeHistory.swift
  SOPKATON-TEAM13/SOPKATON-TEAM13/Data/Model/SignUp/SignUpModel.swift
  SOPKATON-TEAM13/SOPKATON-TEAM13/Presentation/History/Cell/History.swift
  SOPKATON-TEAM13/SOPKATON-TEAM13/Presentation/History/View/HistoryView.swift
  SOPKATON-TEAM13/SOPKATON-TEAM13/Presentation/History/ViewController/HistoryViewController.swift
  SOPKATON-TEAM13/SOPKATON-TEAM13/Presentation/Main/ViewController/MainViewController.swift
  SOPKATON-TEAM13/SOPKATON-TEAM13/Presentation/Main/ViewController/ViewController.swift
  SOPKATON-TEAM13/SOPKATON-TEAM13/Presentation/Notice/Cell/Notice.swift
  SOPKATON-TEAM13/SOPKATON-TEAM13/Presentation/Notice/View/NoticeView.swift
  SOPKATON-TEAM13/SOPKATON-TEAM13/Presentation/Notice/ViewController/NoticeViewController.swift
  SOPKATON-TEAM13/SOPKATON-TEAM13/Presentation/SignUp/Cell/SignUp.swift
  SOPKATON-TEAM13/SOPKATON-TEAM13/Presentation/SignUp/View/SignUpView.swift
  SOPKATON-TEAM13/SOPKATON-TEAM13/Presentation/SignUp/ViewController/SignUpViewController.swift
Labels: Fix, 🐸 정

#17 [Feat] #11 - NoticeViewController 구현
  SOPKATON-TEAM13/SOPKATON-TEAM13.xcodeproj/project.pbxproj
  SOPKATON-TEAM13/SOPKATON-TEAM13.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  SOPKATON-TEAM13/SOPKATON-TEAM13/Application/AppDelegate.swift
  SOPKATON-TEAM13/SOPKATON-TEAM13/Application/SceneDelegate.swift
  SOPKATON-TEAM13/SOPKATON-TEAM13/Data/Model/Notice/NoticeHistory.swift
  SOPKATON-TEAM13/SOPKATON-TEAM13/Network/APIService/History/HistoryService.swift
  SOPKATON-TEAM13/SOPKATON-TEAM13/Network/APIService/Main/MainService.swift
  SOPKATON-TEAM13/SOPKATON-TEAM13/Network/APIService/Notice/NoticeService.swift
  SOPKATON-TEAM13/SOPKATON-TEAM13/Network/APIService/SignUp/SignUpService.swift
  SOPKATON-TEAM13/SOPKATON-TEAM13/Presentation/Notice/Cell/Notice.swift
  SOPKATON-TEAM13/SOPKATON-TEAM13/Presentation/Notice/Cell/NoticeCollectionViewCell.swift
  SOPKATON-TEAM13/SOPKATON-TEAM13/Presentation/Notice/View/NoticeProfileView.swift
  SOPKATON-TEAM13/SOPKATON-TEAM13/Presentation/Notice/View/NoticeView.swift
  SOPKATON-TEAM13/SOPKATON-TEAM13/Presentation/Notice/View/NoticeWeekView.swift
  SOPKATON-TEAM13/SOPKATON-TEAM13/Presentation/Notice/ViewController/NoticeViewController.swift
  SOPKATON-TEAM13/SOPKATON-TEAM13/Resource/AssetCatalog/Color.xcassets/Notice/Contents.json
  SOPKATON-TEAM13/SOPKATON-TEAM13/Resource/AssetCatalog/Color.xcassets/Notice/green1.colorset/Contents.json
  SOPKATON-TEAM13/SOPKATON-TEAM13/Resource/AssetCatalog/Image.xcassets/Notice/Character.imageset/Contents.json
  SOPKATON-TEAM13/SOPKATON-TEAM13/Resource/AssetCatalog/Image.xcassets/Notice/Character.imageset/솝거톤_캐릭터.svg
  SOPKATON-TEAM13/SOPKATON-TEAM13/Resource/AssetCatalog/Image.xcassets/Notice/Contents.json
  SOPKATON-TEAM13/SOPKATON-TEAM13/Utils/NameSpace/Color.swift
Labels: Feat, 🐸 정

#19 [Feat] #16 - MainView 구현
  SOPKATON-TEAM13/SOPKATON-TEAM13.xcodeproj/project.pbxproj
  SOPKATON-TEAM13/SOPKATON-TEAM13.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  SOPKATON-TEAM13/SOPKATON-TEAM13/Application/SceneDelegate.swift
  SOPKATON-TEAM13/SOPKATON-TEAM13/Presentation/Main/View/InnerButtonView.swift
  SOPKATON-TEAM13/SOPKATON-TEAM13/Presentation/Main/View/Main.swift
  SOPKATON-TEAM13/SOPKATON-TEAM13/Presentation/Main/View/neighborButtonView.swift
  SOPKATON-TEAM13/SOPKATON-TEAM13/Presentation/Main/ViewController/MainViewController.swift
  SOPKATON-TEAM13/SOPKATON-TEAM13/Resource/AssetCatalog/Assets.xcassets/MainCharacter.imageset/Contents.json
  SOPKATON-TEAM13/SOPKATON-TEAM13/Resource/AssetCatalog/Assets.xcassets/MainCharacter.imageset/MainCharacter.svg
  SOPKATON-TEAM13/SOPKATON-TEAM13/Resource/AssetCatalog/Image.xcassets/bill.imageset/Contents.json
  SOPKATON-TEAM13/SOPKATON-TEAM13/Resource/AssetCatalog/Image.xcassets/bill.imageset/bill.svg
  SOPKATON-TEAM13/SOPKATON-TEAM13/Utils/Extension/UIButton+.swift
  SOPKATON-TEAM13/SOPKATON-TEAM13/Utils/Extension/UIColor+.swift
Labels: Fix, Feat, 🦊 규보

#22 [Feat] #21 - 로그인 뷰 API 다 붙였당께요?
  SOPKATON-TEAM13/SOPKATON-TEAM13.xcodeproj/project.pbxproj
  SOPKATON-TEAM13/SOPKATON-TEAM13/Application/SceneDelegate.swift
  SOPKATON-TEAM13/SOPKATON-TEAM13/Data/DTO/SignUp/SignUpResponse.swift
  SOPKATON-TEAM13/SOPKATON-TEAM13/Network/LoginService.swift
  SOPKATON-TEAM13/SOPKATON-TEAM13/Presentation/SignUp/ViewController/SignUpViewController.swift
  SOPKATON-TEAM13/SOPKATON-TEAM13/Resource/AssetCatalog/Color.xcassets/yellow.colorset/Contents.json
  SOPKATON-TEAM13/SOPKATON-TEAM13/Utils/NameSpace/Color.swift
Labels: Feat, 🐱 창균

#23 [Feat] #20 MainView 의 API 를 붙였습니다.
  SOPKATON-TEAM13/SOPKATON-TEAM13/Data/DTO/Main/MainResponse.swift
  SOPKATON-TEAM13/SOPKATON-TEAM13/Data/Model/Main/MainModel.swift
  SOPKATON-TEAM13/SOPKATON-TEAM13/Network/APIService/Main/MainService.swift
  SOPKATON-TEAM13/SOPKATON-TEAM13/Presentation/Main/ViewController/MainViewController.swift
Labels: Feat, 🦊 규보
